"""
Simulated complaint cases as they exist in the real system.

In production:
  - SCRIBE already ran and produced the summary
  - TRACE already ran and produced the category
  - Agent already wrote a resolution
  - A sample of these cases is queued for manual review

The LLM Judge grades these cases to reduce that manual review queue.
"""

CASES = [
    {
        "id": "COMP-001",
        # Raw complaint from customer
        "complaint": (
            "I was charged a $35 overdraft fee on March 28th even though I transferred "
            "money into my account the same morning at 9:15 AM. The charge hit at 9:40 AM. "
            "I've been a customer for 11 years. I want the fee refunded and an explanation."
        ),
        # SCRIBE output — summary generated by the summarizer
        "scribe_summary": (
            "Customer charged $35 overdraft fee on March 28 despite depositing funds same morning "
            "at 9:15 AM before the 9:40 AM charge. 11-year customer requesting refund and explanation."
        ),
        # TRACE output — category assigned by the classifier
        "trace_category": "Billing/Fees Dispute",
        # Agent's response to the customer
        "agent_resolution": (
            "We reviewed your account and confirmed the overdraft fee was applied before the "
            "transfer fully processed. As a courtesy we have reversed the $35 fee. Transfers "
            "may take up to 2 hours to reflect depending on the originating bank."
        ),
    },
    {
        "id": "COMP-002",
        "complaint": (
            "Two transactions I did not make appeared on April 1st: $249.99 from StreamPlus EU "
            "and $89 from VPN Shield Pro. I live in Texas, these are European merchants. "
            "My card is still with me. I believe my card details were stolen online."
        ),
        "scribe_summary": (
            "Unauthorized charges of $249.99 (StreamPlus EU) and $89 (VPN Shield Pro) on April 1st. "
            "Customer in Texas suspects online card theft. Card still in possession. Requesting investigation."
        ),
        "trace_category": "Fraud/Unauthorised Transaction",
        "agent_resolution": (
            "Both transactions flagged as fraudulent. Dispute case DSP-20240401-882 opened. "
            "Provisional credits of $249.99 and $89 applied. New card ships in 5 business days."
        ),
    },
    {
        "id": "COMP-003",
        "complaint": (
            "I applied for a home equity loan 6 weeks ago with all documents submitted. "
            "Was told 2–3 weeks processing. No one has contacted me. Emailed loan officer 3 times. "
            "My contractor is waiting and I'm losing money every week."
        ),
        # Slightly inaccurate summary — judge should catch this
        "scribe_summary": (
            "Customer applied for home loan. Processing delayed. Wants a callback."
        ),
        "trace_category": "Loan/Mortgage Complaint",
        "agent_resolution": (
            "We apologise for the delay. Your application is in final approval stage. "
            "Your loan officer will contact you within 48 hours."
            # Vague — does not address financial loss
        ),
    },
    {
        "id": "COMP-004",
        "complaint": (
            "Someone opened a credit card in my name using my SSN. I found it on my credit report — "
            "a FinCore card I never applied for with $4,200 in charges. "
            "I never received the card or any statements. This is identity theft."
        ),
        "scribe_summary": (
            "Fraudulent FinCore credit card opened using customer's SSN without consent. "
            "$4,200 in charges. Customer never received card or statements. Requesting closure and credit report removal."
        ),
        "trace_category": "Fraud/Identity Theft",
        # Intentionally poor resolution — just a redirect with no action
        "agent_resolution": "We are sorry to hear this. Please call our fraud line to report this.",
    },
    {
        "id": "COMP-005",
        "complaint": (
            "Locked out of online banking for 4 days. Called twice, both times promised 24-hour fix. "
            "Still not fixed. Cannot pay bills or check balance. This is unacceptable."
        ),
        "scribe_summary": (
            "Customer locked out of online banking for 4 days. Two support calls made with unfulfilled "
            "24-hour resolution promises. Unable to pay bills or check balance."
        ),
        "trace_category": "Account Access Issue",
        "agent_resolution": (
            "Account was incorrectly flagged in a security review. Flag cleared, access restored. "
            "$25 credit applied as compensation. Allow up to 1 hour for access."
        ),
    },
]
